### ISSUE TITLE
Thumbnail Aspect Ratio with Multiple Monitors

### ISSUE THREAD

**Issue by misho88** [rodakorn/randwall#4]
The thumbnail's aspect ratio takes the entire screen into account. I think something along the lines of the following makes a bit more sense:

const getScreenAspectRatio = function() {
    let screen = Gdk.Screen.get_default();
    let monitor = screen.get_monitor_geometry(screen.get_primary_monitor());
    return monitor.height / monitor.width;
};

**Comment by rodakorn** [comment]
Hi!

Thanks for your suggestion! The very first version of this extension I made, I did it the way you're proposing now, but for users that have more than one monitor and the wallpaper set to "spanned" the image will be deformed because the aspect ratio is calculated only using one screen.

Thanks again for taking the time to suggest improvements ;)

**Comment by rodakorn** [comment]
Oooh sorry... I forgot to tell you that I'm changing the way the aspect ratio is calculated to fix the issue.

**Comment by rodakorn** [comment]
Done! The aspect ratio is calculated taking into account if you have the background set in "spanned".

**Comment by misho88** [comment]
Wow! That was really fast. Thank you!
